spring:
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848 #如果用的云上托管版本，输入可访问的Nacos Server地址即可
      config:
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        group: t-rag
  config:
    import:
      - nacos:t-rag-crm?group=t-rag&refreshEnabled=true
      - nacos:t-rag-base?group=t-rag&refreshEnabled=true
#  data:
#    redis:
#      host: 47.113.118.149
#      port: 36379
#      database: 1
#      password: Yxl123456@
#      # 连接超时时间
#      timeout: 10s
#      lettuce:
#        pool:
#          # 连接池最大连接数
#          max-active: 200
#          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          max-wait: -1ms
#          # 连接池中的最大空闲连接
#          max-idle: 10
#          # 连接池中的最小空闲连接
#          min-idle: 0